### PR TITLE
Update/i3 desktop

### PR DESCRIPTION
**Pull request by musale**
@amol9 I came up with a way to create the wallpaper for i3 window manager. Quite a task scouring through your code (solid stuff btw) but I believe I covered enough. Please review and let me know if any changes are needed.

### CODE REVIEW

**Comment by amol9** [comment]
The PR is incomplete without the following:

1. I3Desktop: set_wallpaper() code introduces dependency on a third party tool (feh) that isn't available by default on many versions of Linux.

A possible solution would be to figure out how i3 wm manages its wallpaper settings and modify those using python code. You may go through code of 'feh' itself (available on github) to see how it does that.

2. I3Desktop: methods: get_wallpaper(), set_wallpaper_style(), get_wallpaper_style() need to be fixed to support i3 wm. Current code uses 'gsettings' which only works for Gnome wm.

3. method get_desktop(): needs to be modified so as to reliably detect i3 wm and return an instance of class I3Desktop.

4. Testing: after fixing code, you need to test to check that all the commands work in i3 wm.

**Comment by musale** [comment]
@amol9 thank you for the feedback. I will look into it during the course of the week.

**Comment by amol9** [comment]
I fixed the code for i3wm, please pull the changes and give it a run.

Notes:
1. 'feh' dependency could not be removed. The code checks for feh and errors out if it is not found.
2. Schedule option won't work on i3. The code for extracting dbus session address doesn't work on i3. I am working on fixing it.

**Comment by amol9** [comment]
The code has been tested on i3wm on kubuntu vm. It works except for the schedule option as mentioned in my previous response. I'll open an issue for that.

**Pull request closed without merging**
